### ISSUE TITLE
"NuLink_M2354 -W APROM ./build/bin/bl2.bin 0" cannot execute

### ISSUE THREAD

**Issue by lwxiaowuge** [OpenNuvoton/Nuvoton_Tools#8]
I Building TF-M code,and Flashing Image with Nuvoton NuLink Tool,NuMaker-PFM-M2354 board supports on board ICE called NuLink. Connect NuLink to PC with USB cable and using [NuLink Command Tool](https://github.com/OpenNuvoton/Nuvoton_Tools) to flashing the image.

The commands are as follows:
 NuLink_M2354 -C
 NuLink_M2354 -E ALL
 NuLink_M2354 -W APROM ./build/bin/bl2.bin 0
 NuLink_M2354 -W APROM ./build/bin/tfm_s_ns_signed.bin 0 0x20000
 NuLink_M2354 -W NSCBA 0x70000

when run command " NuLink_M2354 -W APROM ./build/bin/bl2.bin 0", cannot execute,To quote the following wrong:
$ NuLink_M2354 -W APROM ./build/bin/bl2.bin 0

>>> ERROR: Failed to Parse the Flash Algorithm!!! <<<

********************    Execute operation ending    ********************
CAxf: open file erro

May I ask why?

**Comment by wschang0** [comment]
It seems to be no flash algorithm found.
You may try:

1.      Install Keil driver

https://www.nuvoton.com/resource-download.jsp?tp_GUID=SW1120200221180521

2.      Execute the "NuLink_M2354.exe" in NuLink command tool folder. E.g. C:\Program Files (x86)\Nuvoton Tools\NuLink Command Tool



Regards,
WS

From: lwxiaowuge ***@***.***>
Sent: Monday, May 9, 2022 3:41 PM
To: OpenNuvoton/Nuvoton_Tools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenNuvoton/Nuvoton_Tools] "NuLink_M2354 -W APROM ./build/bin/bl2.bin 0" cannot execute (Issue #8)


I Building TF-M code,and Flashing Image with Nuvoton NuLink Tool,NuMaker-PFM-M2354 board supports on board ICE called NuLink. Connect NuLink to PC with USB cable and using NuLink Command Tool<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenNuvoton%2FNuvoton_Tools&data=05%7C01%7Cwschang0%40nuvoton.com%7Ce947535a09654a3083ed08da318f4f27%7Ca3f24931d4034b4a94f17d83ac638e07%7C0%7C0%7C637876788829564287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p%2BhzCqt2%2Fk8rG2yhIGEcceK2UVgfu5FEkb4caYRRCSc%3D&reserved=0> to flashing the image.

The commands are as follows:
NuLink_M2354 -C
NuLink_M2354 -E ALL
NuLink_M2354 -W APROM ./build/bin/bl2.bin 0
NuLink_M2354 -W APROM ./build/bin/tfm_s_ns_signed.bin 0 0x20000
NuLink_M2354 -W NSCBA 0x70000

when run command " NuLink_M2354 -W APROM ./build/bin/bl2.bin 0", cannot execute,To quote the following wrong:
$ NuLink_M2354 -W APROM ./build/bin/bl2.bin 0

ERROR: Failed to Parse the Flash Algorithm!!! <<<

******************** Execute operation ending ********************
CAxf: open file erro

May I ask why?

-
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenNuvoton%2FNuvoton_Tools%2Fissues%2F8&data=05%7C01%7Cwschang0%40nuvoton.com%7Ce947535a09654a3083ed08da318f4f27%7Ca3f24931d4034b4a94f17d83ac638e07%7C0%7C0%7C637876788829564287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tQVgeA9giOw9TK%2BaYIzy1tIvWxk7EL5tu1%2B8GafcroI%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEM3XD645N4V43Y37XWYOGDVJC6R5ANCNFSM5VNLMSSQ&data=05%7C01%7Cwschang0%40nuvoton.com%7Ce947535a09654a3083ed08da318f4f27%7Ca3f24931d4034b4a94f17d83ac638e07%7C0%7C0%7C637876788829564287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SRB1PH28IgikbP0HWT1PIhiHJeMFtcMPNDTbqxTMN4E%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by lwxiaowuge** [comment]
Yes,Thank you for your answer!
Now,All of the previous steps can be performed，but,Command of "NuLink_M2354 -W NSCBA 0x70000" cannot execute,To quote the following wrong:
C:\Program Files (x86)\Nuvoton Tools\NuLink Command Tool>NuLink_M2354 -W NSCBA 0x70000
>>> ERROR: Command Argument is Incorrect!!! <<<


********************    Execute operation ending    ********************

so, I want konw what does NSCBA mean，and why the command Argument is Incorrect?

**Comment by wschang0** [comment]
Please append ‘0’ to end of the line.

NuLink_M2354 -W NSCBA 0x70000 0

Regards,
WS

**Comment by lwxiaowuge** [comment]
ok，thank you,problem was solved.
